version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 120
      runas: root
    - location: scripts/health_check.sh
      timeout: 120
      runas: root
    - location: scripts/new_switch.sh
      timeout: 120
      runas: root